# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: test notifier

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Notify
      - uses: ./
      - with:
        message: Mayinbun is a shuffled version of Bunyamin
        
